### ISSUE TITLE
The computation of fisher matrix

### ISSUE THREAD

**Issue by Klitter** [seffari/overcoming-catastrophic#1]
I think fisher matrix should be calculated by second derivative of likelihood, but I notices its just uses gradient^2 so that I am confused. Can someone tell me which one is right?

**Comment by yuandixia** [comment]
Using second derivative or gradient^2 can be proved to be the same here, and calculating gradient should be easier. You can find a math proof in the book _Theory of Point Estimation, Second Edition_ by Lehmann & Casella, Lemma 5.3, p. 116.

**Comment by Klitter** [comment]
> Using second derivative or gradient^2 can be proved to be the same here, and calculating gradient should be easier. You can find a math proof in the book _Theory of Point Estimation, Second Edition_ by Lehmann & Casella, Lemma 5.3, p. 116.
Thank you! It is a crude (and biased) approximation.

**Comment by ariseff** [comment]
Thanks @yuandixia for addressing the question.
